data:
  aug: true
  aug_prob: 0.35
  extension: .nii.gz
  mae_root: ../wangdata/data/upload_here/Xinliu/placenta_multiecho_stacks/AllTimeRaw/te_other
  norm_perc: 99.5
  normalize: true
  patch_size:
  # - 96
  # - 96
  # - 96
  - 256
  - 256
  - 256
  remove_bg: true
  src_data: default
  tgt_data: default
  val_img: default
  val_label: default
model:
  depth: 8
  embed_dim: 512
  large_scale: true
  load_pretrain: true
  pretrain_model: default
system:
  ckpt_dir: default
  display_winsize: 128
  exp_name: Plac_MAE
  n_threads: 8
  no_html: false
  project: PROJ
  save_nii: true
  seed: 0
  wandb: true
train:
  batch_size: 4
  betas:
  - 0.9
  - 0.95
  cls_num: 2
  global_mae_patch: 4
  local_mae_patch: 8
  lr: 0.0002
  mask_ratio: 0.7
  niter: 200
  niter_decay: 100
  optimizer: AdamW
  patience: 50
  print_freq: 100
  save_epoch_freq: 50
  test_time: false
  type: mae
  warmup: 10
  weight_decay: 0.05
